### ISSUE TITLE
Problem understanding the code

### ISSUE THREAD

**Issue by JDRanpariya** [KDKHD/CoronaDataScraper#1]
Hi kdkhd,
I didn't get that why you used elasticsearch and made connection and used that as init in worldmeter spider..
so, can you explain  me why you used that and what if we don't use that

**Comment by KDKHD** [comment]
Hi JDRanpariya ,
Thanks for your interest. I created the connection in the spider because I want to store the data in an elastic search database so that I can visualise it on a map. 

If you do not want to use elastic search, you can comment out all of the lines referring to elastic:
``` 
def __init__(self):
        try:
            self.es = elasticSearchApi.es()
        except Exception as e:
            quit()
```
```
self.es.store_data(rowData, index = "corona_daily_worldometer_table", doc_id = dataHash)
```  
```  
self.es.store_data(data, index = "corona_country_worldometer_past", doc_id = dataHash)
```
